# Desktop-only Hyprland settings
monitor= Monitor DP-2, 3840x2160@120.00Hz, 0x0 , 1
monitor= Monitor DP-3, 2560x1440@120.00Hz, 3840x0, 1

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
general:gaps_out = 5
